# Generated by Django 4.2 on 2023-05-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('cart', '0002_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='users',
            field=models.ManyToManyField(to='users.user'),
        ),
    ]
