# Generated by Django 4.2 on 2023-05-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_loyalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
