# Generated by Django 4.2 on 2023-05-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_amount_remove_cart_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
