# Generated by Django 4.2 on 2023-05-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('billing_name', models.TextField()),
                ('billing_address', models.TextField()),
                ('billing_city', models.TextField()),
                ('billing_postal_code', models.TextField()),
                ('billing_country', models.TextField()),
            ],
        ),
    ]
