# Generated by Django 4.2 on 2023-05-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderstatus_is_user_editable_orderstatus_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='is_user_editable',
        ),
    ]
