# Generated by Django 4.2 on 2023-05-11 17:28

from django.db import migrations, models
import orders.validators


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_billing_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='order_status_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_card_number',
            field=models.CharField(null=True, validators=[orders.validators.credit_card_number_validator]),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_cvc',
            field=models.CharField(null=True, validators=[orders.validators.cvc_validator]),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_expiry_month',
            field=models.CharField(null=True, validators=[orders.validators.expiry_month_validator]),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_expiry_year',
            field=models.CharField(null=True, validators=[orders.validators.expiry_year_validator]),
        ),
    ]
