# Generated by Django 4.2 on 2023-05-12 17:56

from django.db import migrations, models
import orders.validators


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_orderstatus_order_status_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_phone_number',
            field=models.CharField(null=True, validators=[orders.validators.phone_number_validator]),
        ),
    ]
