# Generated by Django 4.2 on 2023-05-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=0)),
                ('email', models.TextField(default=0)),
                ('password', models.CharField(max_length=120)),
                ('loyalty_points', models.IntegerField(default=0)),
            ],
        ),
    ]
