# Generated by Django 4.2 on 2023-05-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_loyaltypoints_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltypointstransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoyaltyPoints',
        ),
        migrations.DeleteModel(
            name='LoyaltyPointsTransaction',
        ),
    ]
