# Generated by Django 4.2 on 2023-05-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_o_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='o_template',
            name='offer_ptr',
        ),
        migrations.AddField(
            model_name='o_template',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='o_template',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.offer'),
        ),
    ]
