# Generated by Django 4.2 on 2023-05-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('toppings', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('template',models.CharField(max_length=120)),
            ],
        ),
    ]
