# Generated by Django 4.2 on 2023-05-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='template',
        ),
    ]
