# Generated by Django 4.2 on 2023-05-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productcategory_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='filter',
            field=models.BooleanField(default=False),
        ),
    ]
