# Generated by Django 4.2 on 2023-05-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_offertemplate_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offertemplate',
            name='type',
        ),
    ]
