# Generated by Django 4.2 on 2023-05-10 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_offertemplate_offer_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='products.offer')),
                ('products', models.ManyToManyField(related_name='products', to='products.product')),
            ],
        ),
    ]
