# Generated by Django 4.2 on 2023-05-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_offerinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerinstance',
            name='quantity',
        ),
    ]
