# Generated by Django 4.2 on 2023-05-11 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_offerinstance_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='loyalty_points',
            new_name='loyalty_points_bonus',
        ),
    ]
