# Generated by Django 4.2 on 2023-05-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_offerinstance_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='second_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
