# Generated by Django 4.2 on 2023-05-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_second_picture'),
        ('products', '0011_rename_loyalty_points_only_product_pay_with_loyalty_points'),
    ]

    operations = [
    ]
