# Generated by Django 4.2 on 2023-05-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_loyalty_points_product_loyalty_points_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='new_toppings',
            field=models.ManyToManyField(blank=True, related_name='pizzas', to='products.pizzatopping'),
        ),
    ]
