# Generated by Django 4.2 on 2023-05-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_pizzatopping_pizza_new_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
    ]
