# Generated by Django 4.2 on 2023-05-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_pizza_toppings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='new_toppings',
            new_name='toppings',
        ),
    ]
