# Generated by Django 4.2 on 2023-05-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_new_toppings_pizza_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='loyalty_points',
        ),
    ]
